### ISSUE TITLE
How do I install it

### ISSUE THREAD

**Issue by willbishop** [rigtorp/udpreplay#1]
Dumb question, I know

**Comment by rigtorp** [comment]
$ cd udpreplay
$ make build
$ cd build
$ cmake ..
$ make
$ make install

I should put this in the readme. This is the standard CMake build and install procedure.

Sent from Mail for Windows 10

From: Will Bishop
Sent: Saturday, January 14, 2017 5:37 AM
To: rigtorp/udpreplay
Cc: Subscribed
Subject: [rigtorp/udpreplay] How do I install it (#1)

Dumb question, I know
