### ISSUE TITLE
meet problems while building

### ISSUE THREAD

**Issue by FFChyan** [rigtorp/udpreplay#13]
I wonder if it could be built on MacOS. If so , when I make files it says 
/udpreplay-master/src/udpreplay.cpp:173:40: error: unknown
      type name 'iphdr'
      auto ip = reinterpret_cast<const iphdr *>(p + sizeof(ether_header));
                                       ^
Like this, there are 6 errors. So I can't build it.

My CMake version is 3.12.4, the latest release is 3.14, is that's fault? I have already installed libpcap using pip.

**Comment by rigtorp** [comment]
I have never tried on MacOS. You need to include the system header where `struct iphdr` is defined.

**Comment by rigtorp** [comment]
Please check if PR #16 fixes this issue.
