### ISSUE TITLE
how to replay can socket ! 

### ISSUE THREAD

**Issue by johnchan20** [rigtorp/udpreplay#23]
i use tcpdump to record the can-socket to a file, the file can be open rightly by wireshare and tcpdum,but can not played by udpreplay,please help me

**Comment by rigtorp** [comment]
Udpreplay is specifically for UDP. Maybe try
https://github.com/linux-can/can-utils

**Comment by johnchan20** [comment]
do you have udprecord or udpdump like things，it would be another good light weight program.

**Comment by rigtorp** [comment]
No the idea for udpreplay is to not require root / CAP_NET_RAW for replay. Maybe https://github.com/rigtorp/efvicap/ can help you build it.
