### ISSUE TITLE
sendto: Permission denied

### ISSUE THREAD

**Issue by quark9981** [rigtorp/udpreplay#28]
~/Desktop$ ./udpreplay-x64-linux-static -i eth1 test.pcap
sendto: Permission denied

**Comment by quark9981** [comment]
~/Desktop$ sudo ./udpreplay-x64-linux-static -i eth1 test.pcap
sendto: Permission denied

**Comment by fergian94** [comment]
Hi. I'm having this issue too..anyone solved it?

**Comment by rigtorp** [comment]
Even as root? That's interesting! It's not an issue with udpreplay itself, but I would check:

- Maybe the pcap has a packet with invalid UDP destination IP or port? This could also be udpreplay parsing the headers incorrectly.
- Some selinux policy causes even root to not have permission to transmit for some reason.

Could you provide the pcap file? You can send it to me privately and I will delete it after debugging if that's fine. Otherwise we can try extract only the offending packet using GDB. Let me know.

**Comment by fergian94** [comment]
Hi @rigtorp nice to hear from you.

> Could you provide the pcap file? You can send it to me privately and I will delete it after debugging if that's fine. Otherwise we can try extract only the offending packet using GDB. Let me know.

The pcap i'm using is from Velodyne sample data.
I used the Monterey Highway scenario; you can find it under Software/Sample data HDL-32E, just following this link:
[https://velodynelidar.com/downloads/#software%20first](url)

> * Maybe the pcap has a packet with invalid UDP destination IP or port? This could also be udpreplay parsing the headers incorrectly.

Opening the pcap in wireshark gives:
![image](https://user-images.githubusercontent.com/61280881/135516718-009be305-09c0-423e-b5b0-3bc522340c85.png)
I don't know if this destination IP is invalid or not.

> * Some selinux policy causes even root to not have permission to transmit for some reason..

idk how to check this out. I'm using a mere Ubuntu 20.04 so unless necessary I would first ask try to find the solution in the first point.

Thanks for the reply

**Comment by rigtorp** [comment]
Ah, you need to enable broadcast, that's the `-b` command line flag.

**Comment by fergian94** [comment]
Oh my bad. But is there any way to send packets to loopback? Which is the actual interface I want to use

**Comment by rigtorp** [comment]
I don't know actually, broadcast packets are treated specially. If you figure it out let me know.

**Comment by fergian94** [comment]
Yeah sure. Thanks a lot

Il Gio 30 Set 2021, 22:59 Erik Rigtorp ***@***.***> ha
scritto:

**Comment by xmfcx** [comment]
Lets assume your ip is `192.168.1.78`.

The following will modify all the packets with the destination `255.255.255.255` to `192.168.1.78`:
`tcprewrite -i source.pcap -o target.pcap -D 255.255.255.255/1:192.168.1.78`

And if you want to modify like all `192.168.0.0` to `192.168.255.255` destination range to have your ip:
`tcprewrite -i source.pcap -o target.pcap -D 192.168.0.0/16:192.168.1.78`

For the velodyne driver use cases, in the launch file you can set the [host ip](https://github.com/tier4/nebula/blob/a89c0a91999a2b08942752dd9986b5c3ea0ba067/nebula_ros/launch/velodyne_launch_all_hw.xml#L39) like:
`<arg name="host_ip" value="192.168.1.78"/>`

And it should work fine. `udpreplay -i lo -r 1 target.pcap`

`-b` option floods the whole network and can cause complaints from coworkers.
