### ISSUE TITLE
udpreplay freezes

### ISSUE THREAD

**Issue by Solimatorko** [rigtorp/udpreplay#5]
Resending RTP packets freezes when rtp timestamp from header is lower than previous rtp packet timestamp. Should not happen in perfect RTP stream but in general it's possible.
[freezingPatch.zip](https://github.com/rigtorp/udpreplay/files/1410949/freezingPatch.zip)

**Comment by rigtorp** [comment]
Yeah, this patch makes sense. Can you please create a pull request?

**Comment by axelfurlan** [comment]
This patch made my day! Can you please integrate it into the repo?
Thank you very much!

**Comment by rigtorp** [comment]
I've applied this patch.

**Comment by axelfurlan** [comment]
Great job man!
Thank you very much!
Best
axel
