### ISSUE TITLE
Fragmentation issue 

### ISSUE THREAD

**Issue by rangila** [rigtorp/udpreplay#7]
The library crashes when trying to send UDP packets fragmented at the IP level.

Error messages:
"sendto: message too long" or "sendto: Bad address"

Could you please support me and eventually release a patch?

Thanks,
Aleksey

**Comment by rigtorp** [comment]
If kernel refuses to send messages larger than MTU, I don't think there is anything udpreplay can do about that.

**Comment by rangila** [comment]
Thank you, that's an useful hint for me. I will try to solve the issue by verifying if there's something in the kernel configuration that would allow me to perform this operation.
